name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build leetcode project
      run: cd 98_leetcode && cmake -Bbuild . && cmake --build build
    - name: build project euler
      run: cd 99_project_euler && cmake -Bbuild . && cmake --build build
